defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: plan_outputs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: plan_outputs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 16
    mem_gb: 256
    gres: "gpu:h100:1"
    qos: "explore"
    timeout_min: 720
    setup: ["export DEBUGVAR=$(scontrol show hostnames $SLURM_JOB_NODELIST)",
            export MASTER_ADDR="$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)",
            "export MASTER_PORT=$(for port in $(shuf -i 30000-65500 -n 20); do if [[ $(netstat -tupln 2>&1 | grep $port | wc -l) -eq 0 ]] ; then echo $port; break; fi; done;)",]

# model to load for planning
ckpt_base_path:   # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: null
model_epoch: latest

seed: 0
n_evals: 50
goal_source: 'dset'
goal_H: 5 
n_plot_samples: 0
use_action_encoder: false   # True for baseline
use_lam: true   # false for raw, true for discrete and latent
use_vq: false   #  false for raw, true for discrete
is_training: false # always false 
plan_action_type: "latent"  # "raw" or "latent" or "discrete" | raw = baseline, always run with use_action_encoder=True
use_e: true
use_z: true
use_delta: false
debug_dset_init: False

latent_prior:
  mu: null
  sigma: null
  k: 2.0
  lambda: 0.00
  use_prior_sampling: true

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2
  mode: last

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: 10 
  n_taken_actions: 5
  sub_planner:
    target: planning.cem.CEMPlanner
    horizon: 5
    topk: 30
    num_samples: 300
    var_scale: 1
    opt_steps: 10
    eval_every: 1
    latent_prior_mu: ${latent_prior.mu}
    latent_prior_sigma: ${latent_prior.sigma}
    latent_prior_k: ${latent_prior.k}
    latent_prior_lambda: ${latent_prior.lambda}
    use_prior_sampling: ${latent_prior.use_prior_sampling}
    pseudocount: 1.0
    momentum: 0.7
    min_prob: 0.001
    init_smoothing: 0.05
    sample_temperature: 1.5
    use_mode_as_first_sample: false
    return_mode: false
  name: mpc_cem

