defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: plan_outputs/${now:%Y-%m-%d-%H-%M-%S}_gH${goal_H}
  sweep:
    dir: plan_outputs/${now:%Y-%m-%d-%H-%M-%S}_gH${goal_H}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 16
    mem_gb: 256
    gres: "gpu:h100:1"
    qos: "explore"
    timeout_min: 720
    setup: ["export DEBUGVAR=$(scontrol show hostnames $SLURM_JOB_NODELIST)",
            export MASTER_ADDR="$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)",
            "export MASTER_PORT=$(for port in $(shuf -i 30000-65500 -n 20); do if [[ $(netstat -tupln 2>&1 | grep $port | wc -l) -eq 0 ]] ; then echo $port; break; fi; done;)",]

# model to load for planning
ckpt_base_path: /content/drive/MyDrive/DINO-WM/Model Checkpoints/Tests/14-57-38  # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: null
model_epoch: latest

seed: 99
n_evals: 5
goal_source: 'dset'
goal_H: 5 
n_plot_samples: 10
plan_action_type: "discrete"  # "raw" or "latent" or "discrete" | raw = baseline, always run with use_action_encoder=True
use_action_encoder: false   # True for baseline
use_lam: true   # false for raw, true for discrete and latent
use_vq: true   #  false for raw, true for discrete

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2
  mode: last

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null 
  n_taken_actions: 1
  sub_planner:
    target: planning.discrete_cem.DiscreteCEMPlanner  # when plan_action_type is "discrete" use cem.DiscreteCEMPlanner only 
    horizon: 5
    topk: 30
    num_samples: 300
    var_scale: 1
    opt_steps: 10
    eval_every: 3
    pseudocount: 0.0
    momentum: 0.1
    min_prob: 0.0001
    init_smoothing: 0.0
    sample_temperature: 1.0
    use_mode_as_first_sample: false
  name: mpc_discrete_cem

