_target_: planning.mpc.MPCPlanner
max_iter: 10
n_taken_actions: 1
sub_planner:
  target: planning.cem.DiscreteCEMPlanner
  horizon: 5
  topk: 30
  num_samples: 300
  var_scale: 1
  opt_steps: 30
  eval_every: 1

name: mpc_discrete_cem