_target_: models.vq_ema.VectorQuantizerEMA
num_codes: ${model.num_codes}
code_dim: ${model.codebook_dim}
codebook_splits: ${model.codebook_splits}
ema_decay: ${model.ema_decay}
commitment: ${model.commitment}
